### ISSUE TITLE
Web socket error on homebridge reboot 

### ISSUE THREAD

**Issue by Hucksleyy91** [valiquette/homebridge-orbit-irrigation#17]
![27725BE8-5FC2-4260-B710-8185B782065B](https://user-images.githubusercontent.com/38526744/147304322-313c84ae-7a24-4d80-8d9a-da37bf0437ab.png)

**Comment by valiquette** [comment]
Did this happen on every reboot? Shower only, or any valve type?

**Comment by Hucksleyy91** [comment]
Yeah every reboot that I noticed and I have it set to irrigation as shower isn’t working yet it shows as a tap when you set to shower

**Comment by valiquette** [comment]
I am not able to replicate this. one of the plugin dependancies, WS updated 4 days ago. Can you try re installing the plugin?

**Comment by Hucksleyy91** [comment]
After deleting and reinstalling the plugin I no longer see any errors :) 
Just gotta try get it to show as a shower now ;)
