### ISSUE TITLE
BHyve Faucet Timer not showing

### ISSUE THREAD

**Issue by jcharnet** [valiquette/homebridge-orbit-irrigation#36]
Hello, I have a b-hyve faucet (ORBIT BHYVE 1 OUTLET HOSE TIMER) and the WiFi adapter. 
I have configured the plugin and can see in the logs that everything is detected. However I don’t see any accessory in HomeKit. What am I missing?

Here’s the startup log:
![53BA2601-FEC0-414B-A63D-7C2FB14DA90F](https://user-images.githubusercontent.com/3476125/154203190-39331f9f-9510-4e96-be3b-9b80bdbf15a4.jpeg)

**Comment by valiquette** [comment]
Forgive the silly response. But did you add the accessory in HomeKit? If you added this as a child bridge then you would need to add that bridge separately. If yo have done all this then maybe look at removing cached accessory.

**Comment by jcharnet** [comment]
Not silly at all, very valid. But indeed I did add it HomeKit. I haven't tried removing cached accessory, and that clearly did the trick. Thank you so much.
