### ISSUE TITLE
Can't remove accessories from HomeKit

### ISSUE THREAD

**Issue by dfizzo** [valiquette/homebridge-orbit-irrigation#38]
Hi - I installed the plug-in with Wifi hub exposed. I have been trying everything to remove the Wifi hub exposure. I've uninstalled the plug-in, removed the cached accessories but nothing will work. I am stuck now with multiple b-hyve accessories that are now exposed but don't do anything. Any thoughts? Thanks!

**Comment by valiquette** [comment]
Try removing the bridge for this accessory form HomeKit then re add it. 
I have seen other things like this on the latest IOS.

**Comment by dfizzo** [comment]
I don’t have Orbit plug-in setup with it’s own Homebridge bridge in HomeKit though. Just using the main Homebridge bridge.
________________________________

**Comment by valiquette** [comment]
Ouch!  Using the child bridges really are the way to go.  Only thing I could suggest is adding this one as a child, to get it correct. maybe clear accessories and force restart Homebridge.

I get better performance from HomeKit with multiple bridges, at this point I have nothing tied to the main anymore. I would migrate one at a time until everything was duplicated then remove the main.

**Comment by dfizzo** [comment]
Great idea. If I move everything to child bridges then delete Main Homebridge bridge (where the corrupted Orbit instance remains)…that should fix the orbit isssue (and then reinstall the orbit plug-in)…right? The child bridges will survive right?
________________________________

**Comment by valiquette** [comment]
yes, each child bridge is its own thing and each plugin will look just like a certified HomeKit bridge does in the app.  and when something goes wrong you don't have to rebuild everything.

Please let me know if this corrects things.

**Comment by dfizzo** [comment]
Thanks! This worked great. Really appreciate the guidance!
________________________________

**Comment by dfizzo** [comment]
Btw - wonderful work on the Racho Homebridge! I stopped using native HomeKit for your plug-in recently. Couldn’t handle the native instability issues. You nailed it!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Mar 2, 2022, at 4:21 PM, Daniel Fein ***@***.***> wrote:

﻿
Thanks! This worked great. Really appreciate the guidance!
