### ISSUE TITLE
Struggling with setup, devices being skipped

### ISSUE THREAD

**Issue by benhami1ton** [valiquette/homebridge-orbit-irrigation#39]
So I think I'm close to getting this working, but I seem to be having the same problem of several users of the Bridge skipping over devices because they're not properly recognized in the config. The Bridge can find my account, identify my online BH1-0001 hub and online HT25-0000 valve, however the HT25-0000 valve that is identified as an Irrigation System gets skipped "based on config". In the Home app, I see what looks like the BH1-0001 hub showing up as a device, but understandably no method to manipulate it, since it's just the hub.

I have all booleans set to `true` because I wanted to see what shows up in Homekit, are some of these conflicting or is there a reason the valve is being identified as online but then skipped?

**Comment by valiquette** [comment]
Most of these cases are white space issues from an extra space at the end, typically on the orbit account side. You can double check this in the log as it should state what it is comparing from your config to what is found on your account, if they look the same then there is most likely a space in the mix. You could try to reentering the street address on both to be sure. maybe a copy paste situation. All that said if you only have the one location you can also leave that field blank in which case it will use everything it finds on the account.

**Comment by valiquette** [comment]
I am not sure if you solved this but someone else reported the same issue and attached their config and it appears to be missing the following line after the initial install.
"showIrrigation": true,
