### ISSUE TITLE
Zone switches don't always show up?

### ISSUE THREAD

**Issue by robacarp** [valiquette/homebridge-orbit-irrigation#40]
I'd be surprised if there was anything you're doing in here which would cause this glitch, but I've been using HomeKit and Homebridge devices within it for several years and have never seen anything like this. Perhaps some sort of race condition? It's not easy to reproduce.

https://user-images.githubusercontent.com/208647/163857428-d7491789-2ff5-4f41-a8de-743ba67def14.mp4

**Comment by valiquette** [comment]
This appears to be effecting any app or plugin using an irrigation system device following the list IOS update. 
It seems that if you click the tile it will be blank, yet if you "long" press it will show fine.
This bug does not seem to have any effect if you do not display as an irrigation system. May that will work for a bit until Apple fixes this.

**Comment by homersdonut** [comment]
This is also happening to me - regardless of long press or short tap. 
![image](https://user-images.githubusercontent.com/42158110/167455587-7e6817bb-a79b-4aa0-9209-6a6de97fd697.jpeg)

**Comment by rdstov** [comment]
I have the same issue.

**Comment by robacarp** [comment]
I've since tried out other sprinkler controllers in HomeKit and even Rachio, which natively does their own HomeKit, has this problem. I doubt there's anything that can be done here.

**Comment by valiquette** [comment]
I was able to confirm this issue of not displaying an irrigation system correctly is fixed in IOS16.0 (public beta)

**Comment by homersdonut** [comment]
Thank you! I noticed this as well.On Jul 23, 2022, at 10:37 AM, valiquette ***@***.***> wrote:﻿
I was able to confirm this issue of not displaying an irrigation system correctly is fixed in IOS16.0 (public beta)

**Comment by mgurreta** [comment]
Had this issue with iOS 15... this is no longer an issue with iOS 16. im running the first public beta

**Comment by valiquette** [comment]
Fixed in IOS 16
