### ISSUE TITLE
Skipping all devices

### ISSUE THREAD

**Issue by asander85** [valiquette/homebridge-orbit-irrigation#41]
I am trying to understand the installation instructions and am having difficulty. Messing around with the options on the plugin, I can get the wifi bridges to show up but the plugin wants to skip my actual sprinkler controllers no matter what options I choose. I tried making sure the address matched (which at first they didn't until I realized I had an extra space on one in the B Hyve app) and even after the addresses matched I tried deleting my address from the plugin completely. Still skipping them. The devices on my account are: Front Yard HT31-0001 connected to WiFi Bridge BH1G2-001 in the living room, and Back Yard HT34-0001 connected to WiFi Bridge BH1G2-001 in the kitchen. I don't really see the need to have the wifi bridges visible in HomeKit, I just want to control my sprinklers and see when/if they are running. 

Logs:
4/27/2022, 8:43:57 AMOrbit Irrigation Bridge starting
4/27/2022, 8:44:06 AMOrbit Irrigation BridgeLoaded plugin 'homebridge-orbit-irrigation'
4/27/2022, 8:44:06 AMOrbit Irrigation BridgeLoading 1 platforms...
4/27/2022, 8:44:06 AMOrbit Irrigation BridgeB-HyveStarting Orbit Platform using homebridge API 2.7
4/27/2022, 8:44:06 AMOrbit Irrigation BridgeB-HyveGetting Account info...
4/27/2022, 8:44:07 AMOrbit Irrigation BridgeBridge is running on port 51846.
4/27/2022, 8:44:07 AMOrbit Irrigation BridgeB-HyveFound account for Alex Sander
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveOnline device BH1G2-0001 WiFi Hub Living Room found at the configured location address: 1516 Stonegate Manor Dr
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveOnline device BH1G2-0001 WiFi Hub Kitchen found at the configured location address: 1516 Stonegate Manor Dr
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveOnline device HT31-0001 Front Yard found at the configured location address: 1516 Stonegate Manor Dr
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveOnline device HT34-0001 Back Yard found at the configured location address: 1516 Stonegate Manor Dr
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveSkipping Bridge BH1G2-0001 WiFi Hub Living Room based on config
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveSkipping Bridge BH1G2-0001 WiFi Hub Kitchen based on config
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveSkipping Irrigation System HT31-0001 Front Yard based on config
4/27/2022, 8:44:08 AMOrbit Irrigation BridgeB-HyveSkipping Irrigation System HT34-0001 Back Yard based on config
4/27/2022, 8:44:09 AMOrbit Irrigation BridgeB-HyveOrbit Platform finished loading

Config:

    "platform": "bhyve",
    "name": "B-Hyve",
    "defaultRuntime": 1,
    "email": "sander_alexander@XXXXX.com",
    "password": "XXXXX",
    "useIrrigationDisplay": true,
    "showRunall": true,
    "showSchedules": false,
    "showBridge": false,
    "showStandby": true,
    "displayValveType": "1",
    "locationAddress": "1516 Stonegate Manor Dr"

**Comment by valiquette** [comment]
There is a line missing in the config, i am not sure why and I will have to look at this later.
You can look at the plugin setting and look for the setting to show irrigation system and try to toggle it or just manually add this line to your config, which by the way made all the difference here.
"showIrrigation": true,

**Comment by valiquette** [comment]
Turns our this is a Hoobs issue reading the config file, I have posted a new ticket for manually configuring the plugin.
