### ISSUE TITLE
ERROR Invalid or unexpected token - WARNING No plugins installed.

### ISSUE THREAD

**Issue by RHEGOR1** [valiquette/homebridge-orbit-irrigation#42]
I'm getting the following error when the plugin is trying to launch...

5/3/2022, 1:58:59 PM Orbit Bridge ERROR Error loading plugin "homebridge-orbit-irrigation"
5/3/2022, 1:58:59 PM Orbit Bridge ERROR Invalid or unexpected token
5/3/2022, 1:58:59 PM Orbit Bridge WARNING No plugins installed.
5/3/2022, 1:58:59 PM Orbit Bridge Loading 1 platforms...
5/3/2022, 1:59:00 PM Orbit Bridge Bridge is running on port 51836.

CONFIG:

{
    "accessories": [],
    "platforms": [
        {
            "platform": "bhyve",
            "name": "B-Hyve",
            "defaultRuntime": 1,
            "email": "rhegor1@****.***",
            "password": "********",
            "locationAddress": "90035",
            "useIrrigationDisplay": true
        }
    ]
}

Thanks for any assistance.

**Comment by valiquette** [comment]
I am really not sure what is up based on the error message. The config seems to be missing a few things that I would have expected the plugin to set by default. Are you using homebridge UI? 
The error look like this is a bridge but the config is not showing the bridge setting?
Try adding these lines and see if that resolves your issue.

"platforms": [
	{
		"name": "B-Hyve",
		"email": "username@mail.com",
		"password": "password",
		"locationAddress": "123 Easy St",
		"defaultRuntime": 1,
		"runtimeSource": 0,
		"useIrrigationDisplay": true,
		"displayValveType": 1,
		"showIrrigation": true,
		"showBridge": false,
		"showFloodSensor": false,
		"showTempSensor": false,
		"showLimitsSensor": false,
		"showStandby": false,
		"showRunall": false,
		"showSchedules": false,
		"platform": "bhyve"
	}
]

**Comment by RHEGOR1** [comment]
I added these and I'm getting the following errors in the logs:

5/3/2022, 4:46:24 PMOrbit Bridge starting
5/3/2022, 4:46:29 PMOrbit BridgeLoaded plugin 'homebridge-orbit-irrigation'
5/3/2022, 4:46:29 PMOrbit BridgeLoading 1 platforms...
5/3/2022, 4:46:29 PMOrbit BridgeB-HyveStarting Orbit Platform using homebridge API 2.7
5/3/2022, 4:46:29 PMOrbit BridgeB-HyveGetting Account info...
5/3/2022, 4:46:30 PMOrbit BridgeBridge is running on port 51836.
5/3/2022, 4:46:30 PMOrbit BridgeB-HyveERRORError getting API key {
  "transitional": {
    "silentJSONParsing": true,
    "forcedJSONParsing": true,
    "clarifyTimeoutError": false
  },
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "timeout": 0,
  "xsrfCookieName": "XSRF-TOKEN",
  "xsrfHeaderName": "X-XSRF-TOKEN",
  "maxContentLength": -1,
  "maxBodyLength": -1,
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "application/json",
    "orbit-app-id": "Bhyve Dashboard",
    "User-Agent": "axios/0.26.1",
    "Content-Length": 65
  },
  "method": "post",
  "url": "https://api.orbitbhyve.com/v1/session",
  "data": "{\"session\":{\"email\":\"rhegor1@*****.***\",\"password\":\"**********\"}}",
  "responseType": "json"
}
5/3/2022, 4:46:30 PMOrbit BridgeB-HyveERRORError retrieving API key TypeError: Cannot read properties of undefined (reading 'data')
    at OrbitAPI.getToken (/var/lib/hoobs/orbitbridge/node_modules/homebridge-orbit-irrigation/orbitapi.js:41:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
5/3/2022, 4:46:30 PMOrbit BridgeB-HyveERRORFailed to get info for build TypeError: Cannot read properties of undefined (reading 'data')
    at /var/lib/hoobs/orbitbridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:73:50
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by RHEGOR1** [comment]
OK, after a couple tries, it seems to be working perfect now! Thanks so much!
