### ISSUE TITLE
 QUESTION: Smart Hose Faucet compatibility

### ISSUE THREAD

**Issue by charliegn** [valiquette/homebridge-orbit-irrigation#44]
Hi,

I don't know if this is the correct way to get this question to you so sorry if I've missed the mark here. 

I'm wanting to hookup a wifi controlled hose and also want to be sure that whatever I get is compatible with Hoobs or HomeKit. Do you know if the Orbit 21004 B-hyve Smart Hose Faucet Timer with Wi-Fi Hub ([Amazon Link](https://www.amazon.com/gp/product/B0758NR8DJ)) is supported with your plugin?

**Comment by valiquette** [comment]
That device (HT-25) is supported. I use two of them my self. It will work perfectly with Homebridge, Hoobs may need some manual editing of the config file, but it should work just fine on that platform.

**Comment by Mebbz** [comment]
Hi @valiquette ! Is it compatible with this as well? https://www.amazon.com/Orbit-24637-B-hyve-2-Port-Watering/dp/B09KK433KF?ref_=ast_sto_dp&th=1&psc=1 :)

**Comment by valiquette** [comment]
Sorry for the delay, that device is supported, that is a device I use it myself.
