### ISSUE TITLE
Skipping Irrigation System WT24-0001 Sprinkler Timer based on config

### ISSUE THREAD

**Issue by davethis** [valiquette/homebridge-orbit-irrigation#45]
Hi

Using HOOBS

Maybe it is skipping the timer because it is not supported?  But wanted to run this by you and check.  There are not errors showing in the log.

> 6/11/2022, 2:15:37 PMOrbit Irrigation Bridge starting
> 6/11/2022, 2:15:40 PMOrbit Irrigation BridgeLoaded plugin 'homebridge-orbit-irrigation'
> 6/11/2022, 2:15:40 PMOrbit Irrigation BridgeLoading 1 platforms...
> 6/11/2022, 2:15:40 PMOrbit Irrigation BridgeB-HyveStarting Orbit Platform using homebridge API 2.7
> 6/11/2022, 2:15:40 PMOrbit Irrigation BridgeB-HyveGetting Account info...
> 6/11/2022, 2:15:41 PMOrbit Irrigation BridgeBridge is running on port 55555.
> 6/11/2022, 2:15:41 PMOrbit Irrigation BridgeB-HyveFound account for XXXX XXXX
> 6/11/2022, 2:15:41 PMOrbit Irrigation BridgeB-HyveOnline device WT24-0001 Sprinkler Timer found at the configured location address: XXXX Camelia Dr
> 6/11/2022, 2:15:41 PMOrbit Irrigation BridgeB-HyveSkipping Irrigation System WT24-0001 Sprinkler Timer based on config
> 6/11/2022, 2:15:42 PMOrbit Irrigation BridgeB-HyveOrbit Platform finished loading

> {
>     "name": "B-Hyve",
>     "email": "XXXX@gmail.com",
>     "password": "XXXXXX",
>     "locationAddress": "XXXX Camelia Dr",
>     "defaultRuntime": 1,
>     "useIrrigationDisplay": true,
>     "displayValveType": 1,
>     "showBridge": false,
>     "showStandby": false,
>     "showRunall": false,
>     "showSchedules": false,
>     "_bridge": {
>         "username": "D28:32:52:26:70:D5",
>         "port": 55555
>     },
>     "platform": "bhyve"
> }

If this timer is not supported currently, I am happy to try and help any way I can.  

Thanks

**Comment by valiquette** [comment]
This is an issue with HOBBs, for some reason is does not like the format of the configuration file and just omits a key line. 

add this line to your configuration, then it should work just fine
"showIrrigation": true,

because it is missing it assume false which is why you see the log that it skipping it based on the configuration

Also if you have any flood sensors you can add these lines set to true.
            "showFloodSensor": false,
            "showTempSensor": false,
            "showLimitsSensor": false,

**Comment by davethis** [comment]
Thanks that worked!!
