### ISSUE TITLE
Setting to change from sprinkler to a shower or faucet icon in homekit

### ISSUE THREAD

**Issue by Hucksleyy91** [valiquette/homebridge-orbit-irrigation#5]
Setting to change from sprinkler to a shower or faucet icon in homekit for the water valve

**Comment by valiquette** [comment]
It looks like there may be an option for a generic faucet, but not for the shower. I suspect this is because the base is the irrigation system. I can look at this a little more.

**Comment by valiquette** [comment]
I have published a release that will let you select the valve type. That said the only two type that seem to work are the spigot and the irrigation, I am not sure why this is. You will have to uncheck display as irrigation and show as separate tiles. The controller will still be there for the battery service.

**Comment by Hucksleyy91** [comment]
> I have published a release that will let you select the valve type. That said the only two type that seem to work are the spigot and the irrigation, I am not sure why this is. You will have to uncheck display as irrigation and show as separate tiles. The controller will still be there for the battery service.

Your a legend I will test it out

**Comment by Hucksleyy91** [comment]
it wont show as a shower it shows as a tap when set to shower
you also have to uncheck "display as irrigation system in homekit" for it to work

**Comment by valiquette** [comment]
It turned out it will be more complicated than I was hoping, but I do have a plan to provide a simple valve accessory which sounds like what you're looking for.

**Comment by Hucksleyy91** [comment]
would be good if you can select any type in homekit as the icon/type otherwise i look forward to testing the next version

**Comment by valiquette** [comment]
Faucet or Shower valves will not work with an irrigation system accessory. They will only work correctly with a Faucet accessory which also required hot/cold settings, to see the shower head requires multiple heads.
