### ISSUE TITLE
Increase timer to 4 hours

### ISSUE THREAD

**Issue by jbuttnz** [valiquette/homebridge-orbit-irrigation#55]
Is is possible for the maximum timer option to be increased from 1 hour to 4 hours?

**Comment by valiquette** [comment]
No, the Orbit side will only allow a 240 min duration to be set in their UI. I have not tried to exceed this.
I am not sure what you are trying to do exactly. You may be able to create a program on Orbit side that would run the zone the way you want and expose that program to the plugin so HomeKit can start/stop it.

**Comment by jbuttnz** [comment]
I use Ecowitt soil moisture sensors to automatically open Orbit valves. Was hoping to irrigate for over an hour but I understand the limitation of Homekit. Apprecate the quick resopone.
