### ISSUE TITLE
Each faucet shows as two accessories

### ISSUE THREAD

**Issue by linkx2252** [valiquette/homebridge-orbit-irrigation#56]
Hi, is there anyway to make it show as one accessory per faucet?

I have two smart faucets, but in homekit it shows two different accessories for each - 4 total. Two valves, 2 sprinklers.

Really I'd just want it as two sprinklers - these are smart faucets connected/acting as sprinklers.

![0A883DBA-B459-408B-A303-D78BD7A7C66A](https://user-images.githubusercontent.com/74163581/232248953-d0730de7-22c0-488c-9156-dec6f26166c7.png)
<img width="789" alt="Screenshot 2023-04-15 at 3 10 22 PM" src="https://user-images.githubusercontent.com/74163581/232248987-a66ada64-ca0b-4b90-9f89-f9b263c048b1.png">

**Comment by valiquette** [comment]
I see what is going on, basically it is working as designed, these device are really single zone irrigation systems. You may want to try displaying as an irrigation system that will at least remove how things show twice. If this is the smart hose timer with one zone then I can work on having another option to just display that as a single faucet. I have it working but will need some time to test it.

**Comment by linkx2252** [comment]
Easy fix - checking display as irrigation system combined the two
accessories into one. Thanks!

**Comment by linkx2252** [comment]
Spoke too soon - it still shows as two accessories once turned on. If it’s
an easy fix let me know but don’t kill yourself over it.

**Comment by valiquette** [comment]
Try restarting HomeKit or cleaning out a single accessory in hombridge or worse remove and re add the accessory.
