### ISSUE TITLE
Cannot add a Service with the same UUID as another Service in this Accessory without also defining a unique 'subtype' property.

### ISSUE THREAD

**Issue by pramitr** [valiquette/homebridge-orbit-irrigation#57]
This was after removing the bridge from Homekit. I tried restarting the plugin, then restarting homebridge, and finally a fresh install of Homebridge. The error remains the same. There is no bridge or device visible in Homekit any more, so nothing else to do.

The orbit plugin keeps reconnecting with b-hyve, fetches the device list and shows this error in a never-ending loop.

```
Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:552:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:98:41)
    at /usr/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:215:28
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:210:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[4/21/2023, 3:27:01 PM] [B-Hyve] Child bridge process ended
[4/21/2023, 3:27:01 PM] [B-Hyve] Process Ended. Code: 1, Signal: null
```

**Comment by valiquette** [comment]
are you installing this new or has you been using this for a while now?
Based on the section of log you attached, this is coming from a section of code that is trying to add a switch for each schedule. You must has more than one schedule and the plugin is trying to add one with the same UUID it previously created, might have something to so with how they are named, you would not see this it crashed before it can add them. I will fix plugin crashing on this error and I will fix the error. I am pretty sure I can reproduce. 
If you un check the option to show addition switches for schedule or set the config line "showSchedules": false.  This should boot up fine.

**Comment by pramitr** [comment]
This is not a new installation, but yes I am trying to expose schedules as switches. I wanted to have control of the individual zones for automation. But the zones are not exposed as switches. So I created inactive schedules from B-hyve (each having an individual zone) and wanted to expose those as switches. This problem started after that.

**Comment by valiquette** [comment]
Can you share what those scheduled look like? 
What kind of automation are you looking for, and is it something that is not available if uncheck show as irrigation system? I am working on an option that would show each zone as an individual valve accessory.

**Comment by valiquette** [comment]
No matter what I try I cannot replicated the crash. The plugin UUID is the schedule id that get returned when the zones are queried, not matter what I try they always comeback with a unique value. Where did you build these programs, the IOS app, tech support.orbitbhyve.com or my.orbitbhyve.com?

**Comment by pramitr** [comment]
The watering programs were created in iOS app. I have now deleted those and it is now working fine. I have 5 zones named Z1, Z2.. Z5. Previously I created programs for 4 of them with the names like Side Z2, Back Z3, Back 4 and Side 5. I have one more program which is actually active and the rest were inactive.

**Comment by pramitr** [comment]
I figured out how to reproduce the issue. 

In B-Hyve iOS app, there are program slots labeled as A, B, C and D.
If I create a program outside of those slots, it gets hidden under the "Saved Programs" menu.
![IMG_1363](https://user-images.githubusercontent.com/22233236/234126364-f295e94d-342c-4048-adce-803b7c8e5c15.jpeg)
If I create any program outside of these slots, no matter how it is named or whatever zone it contains, it brings up the error loop after restarting Homebridge.
The "Test" program below creates the issue.
![IMG_1361](https://user-images.githubusercontent.com/22233236/234127030-2ab317e0-aba2-4674-a9f9-04678acf3b60.jpeg)

**Comment by valiquette** [comment]
Thanks, this is helpful. I was able to reproduce the error identically by replacing the program name with a null value, which make sense. Orbit starts a program based on name, I need to figure out that part.

**Comment by valiquette** [comment]
I was able to reproduce this for myself, you can only add a disable zone like this in the IOS app and I am not sure how long that ability has been there. I was able to correct this. I have some other changes that I need to finish up before I publish the update.  The next update may have the support for automation you're looking for without this.
Thank you

**Comment by valiquette** [comment]
Fixed in latest release. 
HomeKit will not allow any direct automation for water.
