### ISSUE TITLE
Accessories must be created with a non-empty displayName

### ISSUE THREAD

**Issue by deflao** [valiquette/homebridge-orbit-irrigation#65]
Hello, I’m having a problem with the accessories name. The error is:
![IMG_4644](https://github.com/valiquette/homebridge-orbit-irrigation/assets/90084270/4dd7fd32-e54d-4f23-a98f-80f639dbe010)
I don’t know how to fix this. As soon as I try to expose the hose timer it will give me that error.

**Comment by valiquette** [comment]
I can address the restart but I am not sure what the root issue is. it seems there is a zone with no name configured. I have seen some issue with how the app works and it allows some things to be configured that can not be done on their web page.

Try looking at your account /configuration on this site https://techsupport.orbitbhyve.com and make sure it looks correct.

**Comment by valiquette** [comment]
I was able to duplicated by removing the name for a device, and I have addressed the crash. Make sure your device has a name assigned to it. If it does not have a name one will be assigned.
