### ISSUE TITLE
Unable to Use RunAll

### ISSUE THREAD

**Issue by viper991** [valiquette/homebridge-orbit-irrigation#66]
When the RunAll is set to true, the switch shows up in Homekit but when I try to turn it on an error is thrown.  

7/4/2023, 10:55:23 AMOrbit Irrigation BridgeERROR[Orbit Irrigation Bridge@SPR@SPR Run All@On] Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'defaultRuntime')

Here is the configuration (removed user&password).  It appears to have a defaultRuntime set.  All other functions appear to work (Schedule Run, Standby/Off, selecting individual zones).
{
    "platform": "bhyve",
    "name": "B-Hyve",
    "defaultRuntime": 10,
    "runtimeSource": 1,
    "displayValveType": 1,
    "showIrrigation": true,
    "showRunall": true,
    "email": "xxxxxx",
    "password": "xxxxxx",
    "useIrrigationDisplay": true,
    "showSchedules": true,
    "locationAddress": "xxxxxxxxx",
    "showStandby": true,
}
Thank you.

**Comment by valiquette** [comment]
Thanks for letting me know about this. I have it correct and should publish an update soon.

**Comment by valiquette** [comment]
Corrected in v1.2.20
