### ISSUE TITLE
Restarting Homebridge removes it from the room in HomeKit

### ISSUE THREAD

**Issue by emtz1977** [valiquette/homebridge-orbit-irrigation#70]
Anytime I restart homebridge, both my B-Hyve Hose Timer and irrigation System Accessory with zones are moved out of the assigned room and into the default room.

**Comment by valiquette** [comment]
What version are you running?
I just did the IOS upgrade yesterday, restarted the plugin just now and saw what you described, I moved them back to the room I want them in and they are staying after both a child bridge restart and homebridge restart.
I'll keep looking

**Comment by valiquette** [comment]
I was able to reproduce this again, not sure how but also see the same on another plugin so maybe tied to the IOS update.

**Comment by valiquette** [comment]
Seems corrected in v1.2.22
