### ISSUE TITLE
Plugin not showing up in home app?

### ISSUE THREAD

**Issue by droopdog7** [valiquette/homebridge-orbit-irrigation#76]
As the title says, the plug in is installed but nothing seems to happen in home app.  Settings are straight forward except for address.  Not sure if city, state, etc should be separated by commas or nothing or something else?  Can't figure any other issues that I might be missing?

**Comment by valiquette** [comment]
The address is simple, it is just the street address and it need to match the Orbit side, like "123 Main St" or just leave blank if you only have one location. For this to show up in the home app you will need to pair it. 
<img width="1015" alt="image" src="https://github.com/valiquette/homebridge-orbit-irrigation/assets/66563472/9b09e557-2662-4e9f-aa11-af00fae7f7b1">
click on the left most icon on the bottom right.

**Comment by droopdog7** [comment]
> The address is simple, it is just the street address and it need to match the Orbit side, like "123 Main St" or just leave blank if you only have one location. For this to show up in the home app you will need to pair it. ![image](https://user-images.githubusercontent.com/66563472/268506175-57a55cd0-ac22-4afd-8ab8-4197d8c0a33b.png)
> 
> click on the left most icon on the bottom right.

Thanks.  The simple street address worked!
